name: Scrape
permissions:
  contents: write      # allow the GITHUB_TOKEN to push commits

on:
  schedule:
    - cron: '0 1 * * *'   # 01:00 UTC every day
  workflow_dispatch:       # enables the “Run workflow” button

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4          # latest major

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python -m scraper   # or  python scraper.py

      - name: Commit & push updated data
        uses: EndBug/add-and-commit@v9     # current major
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: Latest data

      - name: Notify webhook
        if: ${{ success() }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST "$WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d '{"status":"success","timestamp":"'"$(date --utc +%FT%TZ)"'"}'
