name: Scrape

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: 'Create virtual environment and activate'
      run: |
        python -m venv .venv
        source .venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run scraper
      run: |
        python -m scraper.py
    - name: Git status
      run: git status
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
    - name: Push
      run: git push
